<?php $years = $this->getPostYears(); ?>

<?php if ( is_array($years) && !empty($years) ): ?>
	<?php $postsBaseUrl = $this->getPostsBaseUrl(); ?>
    <p>Sort:
		<?php foreach ( $years as $year ): ?>
            <a href="<?php echo $postsBaseUrl ?>?year=<?php echo $year; ?>"><?php echo $year; ?></a>
		<?php endforeach; ?>
    </p>
<?php endif; ?>

<?php
$yearFilter = isset($_GET['year']) ? $_GET['year'] : null;

if ( is_null($yearFilter) ) {
	$posts = $this->getPosts();
} else {
	$posts = $this->getPostsByYear($yearFilter);
}

if ( empty($posts) ) {
	$posts = [];
}
?>

    <div id="messages_product_view">
		<?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
		<?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
    </div>

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ( $posts as $post ): ?>

	<?php
	$href = $post->getAddress();
	if ( empty($href) ) {
		$href = "{$this->getPostsBaseUrl()}/{$post->getIdentifier()}";
	}
	?>


    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $href; ?>"><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php echo $post->getCreatedTime(); ?></h3>
        </div>
        <div class="postContent std"><?php echo $post->getPostContent(); ?></div>

		<?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
        <div class="postDetails">
			<?php if ( $this->getCommentsEnabled() ): ?>
				<?php echo $post->getCommentCount(); ?> <a
                        href="<?php echo $post->getAddress(); ?>#commentBox"> <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
			<?php endif; ?>
			<?php $postCats = $post->getCats(); ?>
			<?php if ( !empty($postCats) ): ?>
				<?php echo Mage::helper('blog')->__('Posted in'); ?>
				<?php foreach ( $postCats as $data ): ?>
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
				<?php endforeach; ?>
			<?php else: ?>
				<?php echo Mage::helper('blog')->__('Posted'); ?>
			<?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>